[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "bioimageio.engine"
version = "0.1.0"
readme = "README.md"
description = "BioEngine: Your AI Engine for Advanced BioImage Analysis in Containers"
dependencies = [
  "imjoy-rpc",
  "PyYAML",
  "hypha-launcher",
  "pyotritonclient"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["bioimageio*"]
exclude = ["tests*", "scripts*"]
