on:
  push:
    branches:
      - main

name: Build

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write # for Git to git push
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.9
          conda-channels: anaconda, conda-forge
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      # - name: Test server
        # run: python -m bioimageio.engine start-server --host=0.0.0.0 --port=9000 & wget http://127.0.0.1:9000/public/services/bioengine
